version: "3.8"

services:
  db:
    image: postgres:14-alpine
    container_name: tradeview_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tradeview
    ports:
      - "5422:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
