interface CoinName {
  shortName: string;
  fullName: string;
}

const coinNames: CoinName[] = [
  { shortName: "BTC", fullName: "Bitcoin" },
  { shortName: "ETH", fullName: "Ethereum" },
  { shortName: "USDT", fullName: "Tether" },
  { shortName: "SOL", fullName: "Solana" },
  { shortName: "SHIB", fullName: "Shiba Inu" },
  { shortName: "LINK", fullName: "Chainlink" },
  { shortName: "PEPE", fullName: "Pepe" },
  { shortName: "UNI", fullName: "Uniswap" },
  { shortName: "RENDER", fullName: "Render" },
  { shortName: "BONK", fullName: "Bonk" },
  { shortName: "POLY", fullName: "Polygon" },
  { shortName: "WIF", fullName: "Dogwifhat" },
  { shortName: "AAVE", fullName: "Aave" },
  { shortName: "RAY", fullName: "Raydium" },
  { shortName: "JUP", fullName: "Jupiter" },
  { shortName: "PYTH", fullName: "Pyth" },
  { shortName: "WLD", fullName: "Worldcoin" },
  { shortName: "ONDO", fullName: "Ondo" },
  { shortName: "LDO", fullName: "Lido" },
  { shortName: "HNT", fullName: "Helium" },
  { shortName: "STRK", fullName: "Starknet" },
  { shortName: "MEW", fullName: "Cat in a dogs world" },
  { shortName: "BOME", fullName: "Book of Meme" },
  { shortName: "W", fullName: "Wormhole" },
  { shortName: "BLUR", fullName: "Blur" },
  { shortName: "MOODENG", fullName: "Moo Deng" },
  { shortName: "ZRO", fullName: "LayerZero" },
  { shortName: "JTO", fullName: "Jito" },
  { shortName: "DRIFT", fullName: "Drift" },
  { shortName: "IO", fullName: "Io.net" },
  { shortName: "HONEY", fullName: "Hivemapper" },
  { shortName: "KMNO", fullName: "Kamino" },
  { shortName: "WEN", fullName: "Wen" },
  { shortName: "CLOUD", fullName: "Sanctum" },
  { shortName: "MOBILE", fullName: "Helium Mobile" },
  { shortName: "TNSR", fullName: "Tensor" },
  { shortName: "ZKJ", fullName: "Polyhydra Network" },
  { shortName: "PRCL", fullName: "Parcl" },
  { shortName: "MOTHER", fullName: "Mother Iggy" },
  { shortName: "DBR", fullName: "DeBridge" },
  { shortName: "SHFL", fullName: "Shuffle" },
  { shortName: "MAX", fullName: "Matr1x" },
  { shortName: "MON", fullName: "MON Protocol" },
  { shortName: "ZEX", fullName: "Zeta" },
  { shortName: "NYAN", fullName: "Nyan Heroes" },
  { shortName: "HABIBI", fullName: "Habibi (sol)" },
  { shortName: "ACT ", fullName: "Act I The AI Prophecy" },
  { shortName: "GOAT", fullName: "Goatseus Maximus" },
];

export default coinNames;
